name: Flask CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd main
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          cd main
          export PYTHONPATH=$(pwd)
          pytest

      - name: Build Docker image
        run: |
          cd main
          docker build -t flask-lab-project .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag flask-lab-project ${{ secrets.DOCKERHUB_USERNAME }}/flask-lab-project:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-lab-project:latest
